### ISSUE TITLE
"Fix Permissions" causes big trouble in Lollipop

### ISSUE THREAD

**Issue by jpgonzal** [TeamWin/Team-Win-Recovery-Project#448]
Something changed in lollipop that makes "Fix Permissions" not only not work, but break many things (from boot loops, to sd card access permissions to soft bricking of the phone). In my case I did it accidentally on an HTC One M7 in lollipop 5.02. Only solution was factory reset. Please fix this, or at least give a big warning! Other people have had this problem (https://www.reddit.com/r/Android/comments/2uj8bt/dont_ever_run_fix_permissions_in_twrp_on_a/) ...

**Comment by kerlerm** [comment]
I second that. I soft bricked my phone when selecting "fix permissions" due to other problems on my Galaxy Nexus (maguro) with cm-12.1 and TWRP 2.8.1.0.

Symptoms are unaccessable DB files resulting in boot loops or stuck boot:

```
E/SQLiteLog( 1411): (14) os_unix.c:30052: (13) open(/data/data/com.android.providers.settings/databases/settings.db) - 
E/SQLiteDatabase( 1411): Failed to open database '/data/data/com.android.providers.settings/databases/settings.db'.
E/SQLiteDatabase( 1411): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
E/SQLiteDatabase( 1411):        at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
[...]
W/ThemeUtils( 1411): Unable to open /data/data/com.android.providers.settings/databases/settings.db
W/ThemeUtils( 1411): android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
W/ThemeUtils( 1411):    at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
[...]
```

$ restorecon-R /data did not help

Only nandroid restore of complete partition got me a working phone again.

**Comment by CaptainThrowback** [comment]
That's why the option was removed ;)

**Comment by kerlerm** [comment]
Ay, Ok. I would upgrade to twrp 3.0.2-0 if I only could find an image for maguro...

**Comment by shaggyskunk** [comment]
I believe that 2.8.7.0 is available for your device - AND it's a definite
update on the version that you seem to be using?

**Comment by n76** [comment]
There appears to be a twrp 3.0.2 for Maguro as indicated by this post: http://forum.xda-developers.com/galaxy-nexus/development/recovery-twrp-2-7-1-0-touch-recovery-t1592689/post66467639#post66467639

I haven't tried it so I can't say how well it works.

**Comment by kerlerm** [comment]
2.8.7.0 can't handle encrypted partitions correctly. But I'll have a go with version 3. Thanks for the hint!

**Comment by shaggyskunk** [comment]
Np - I don't have your device - But I'd head a while back that Fix
Permissions didn't work for a number of devices anyway
